---
 - name: install system devel packages
   dnf: name={{ item }} state=present
   with_items:
       - git
       - gcc
       - make
       - vim
       - unzip
       - moreutils-parallel
       - libsodium-devel
